[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://labflow-clinic-backend-skzx.onrender.com"
  VITE_APP_ENV = "production"

[context.deploy-preview.environment]
  VITE_API_URL = "https://labflow-clinic-backend-skzx.onrender.com"
  VITE_APP_ENV = "preview"

[context.branch-deploy.environment]
  VITE_API_URL = "https://labflow-clinic-backend-skzx.onrender.com"
  VITE_APP_ENV = "development"
